num1= int ( input(" Enter first number:") )
num2= int( input(" Enter second number:") )
print(" Addition =" + str(num1 + num2))
print(" Subraction ="+ str(num1 - num2))
print("Multiplication = " + str(num1 * num2))
print("Division = " + str(num1 / num2))